### ISSUE TITLE
Allow empty lists

### ISSUE THREAD

**Issue by jeremy-yamuti** [remigermain/nested-multipart-parser#8]
Hey !

I found this library allowing multipart and nested writable data very helpful, thanks!

I encountered an issue when doing a PATCH request on a nested writable list serializer. I don't see how I can tell the difference between "not providing the attribute" (ie keep its existing value) and "ask to clear the list" (ie delete all elements in the list).

I think being able to provide an empty list would solve this issue, but looking at the code, I can't see any way to do it currently.

Here is an example of how it may work:
```python
class SerializerWithNestedWritableList:
    some_list = SomeIntegerSerializer(many=True, required=False)

# No changes to current value
request.patch(url, data={})

# Replace all values by [1, 2, 3] 
request.patch(url, data={
    "some_list[0]": 1,
    "some_list[1]": 2,
    "some_list[2]": 3,
})

# Remove all values (empty list)
request.patch(url, data={
    "some_list[]": "",  # option 1
    "some_list": "",  # option 2
    "some_list": "[]",  # option 3
})
```

I think option 1 is the better, but I don't mind if any other option is selected.

Regards,

**Comment by remigermain** [comment]
Hi, thx for report, im working on it.
Your dirst solutions will be nice , same of dict like `"obj.": None` for empty dict.

**Comment by jeremy-yamuti** [comment]
Thank you very much Remi! I'll check that immediately :)
